### ISSUE TITLE
References clarification

### ISSUE THREAD

**Issue by LukasLauterbach** [ununhexium/cecho#2]
The spec states the following:

> Unlike printf where the order of arguments is forced, cecho may use arguments in **any order with %x where x is an integer** referring to the arguments passed to cecho.

However, the example below shows this:
`cecho '{3} {2} {1}' a b c`

Shouldn't it be `cecho '{%3} {%2} {%1}' a b c` according to the spec?
Or is it a special case since the specifier only contains a number and nothing else?

Also the examples markdown file only uses `{%n}` instead of `{n}` right now.

Maybe the spec should be more clear about this.

**Comment by ununhexium** [comment]
> Shouldn't it be cecho '{%3} {%2} {%1}' a b c according to the spec?

Correct. Classic doc diverging from the code problem... Fixed in `ec45999` edit: and `c707a73`.

>  Or is it a special case since the specifier only contains a number and nothing else?

Not a special case. I have ideas for expressions like `{some string here#blue}` that would display `some string here` in blue and supporting bare indices would conflict with this. Still pondering if this would be a good or a bad idea...

**Comment by LukasLauterbach** [comment]
Thanks for the clarification!
